### ISSUE TITLE
Collaborating with kamranahmedse

### ISSUE THREAD

**Issue by foopod** [taniarascia/roadmap#1]
Just noticed your new repo. Very cool.

This morning I also came across https://github.com/kamranahmedse/developer-roadmap, which I think has a similar goal, but is maybe more broad. For example the basics section for HTML, CSS and JS doesn't include anything specific.

Just letting you know in case you are interested in collaborating.

😄

**Comment by taniarascia** [comment]
Hi! This is the beginnings of a little outline for what I hope to eventually become a complete course that I write. It's not going to be a map of technologies or a list of frameworks. It's going to be very in-depth, and hopefully solve the issue of newbies having to find sources written by dozens of people that all cover the same things over and over yet skip essentials in-between. Therefore, these two repos don't have a similar goal. But it's a good resource!

**Comment by foopod** [comment]
Awesome! I am super looking forward to it 😄
